# Generated by Django 3.1.7 on 2021-03-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuAlgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_id', models.IntegerField()),
                ('algo_name', models.CharField(max_length=50)),
                ('algo_discription', models.TextField()),
            ],
        ),
    ]
