# Generated by Django 3.1.7 on 2021-03-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_auto_20210314_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpualgo',
            name='algo_code',
            field=models.TextField(default='null'),
        ),
    ]
